# Generated by Django 3.0.3 on 2020-11-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0002_donate_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate_images',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='donateImages/'),
        ),
    ]
