# Generated by Django 3.0.3 on 2020-11-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0005_auto_20201111_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate_post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='donate_images/'),
        ),
    ]
