# Generated by Django 3.0.3 on 2020-11-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0006_donate_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate_post',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='donate_images/'),
        ),
        migrations.DeleteModel(
            name='Donate_Images',
        ),
    ]
