# Generated by Django 3.0.3 on 2020-11-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0007_auto_20201111_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donate_post',
            name='id',
        ),
        migrations.AlterField(
            model_name='donate_post',
            name='title',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
