# Generated by Django 3.0.3 on 2020-11-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0008_auto_20201111_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate_post',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donate_post',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
