# Generated by Django 3.0.3 on 2020-11-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0010_auto_20201111_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate_post',
            name='is_requested',
            field=models.BooleanField(default=False),
        ),
    ]
