# Generated by Django 3.0.3 on 2020-11-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0011_donate_post_is_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate_post',
            name='type',
            field=models.CharField(choices=[('CLOTHES', 'CLOTHES'), ('BOOKS', 'BOOKS'), ('TOYS', 'TOYS'), ('FURNITURE', 'FURNITURE')], default='CLOTHES', max_length=20),
        ),
    ]
