# Generated by Django 3.0.3 on 2020-11-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0012_donate_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate_post',
            name='is_acc_for_transport',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='donate_post',
            name='to_city',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='donate_post',
            name='to_country',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='donate_post',
            name='to_doorNo',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='donate_post',
            name='to_person',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='donate_post',
            name='to_pinCode',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='donate_post',
            name='to_residence',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AddField(
            model_name='donate_post',
            name='to_state',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='donate_post',
            name='to_street',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
