# Generated by Django 3.0.3 on 2020-11-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0013_auto_20201122_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate_post',
            name='mail_sent',
            field=models.BooleanField(default=None),
        ),
    ]
