# Generated by Django 3.0.3 on 2020-11-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0014_donate_post_mail_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate_post',
            name='mail_sent',
            field=models.BooleanField(default=False),
        ),
    ]
