# Generated by Django 3.0.3 on 2020-12-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0015_auto_20201127_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donate_post',
            name='type',
        ),
        migrations.AddField(
            model_name='donate_post',
            name='availableitems',
            field=models.CharField(choices=[('Clothes', 'Clothes'), ('Food', 'Food'), ('Toys', 'Toys'), ('Books', 'Books'), ('Others', 'Others')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
