# Generated by Django 3.0.5 on 2020-12-02 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupoun', '0002_auto_20201202_2354'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gencode',
        ),
    ]
