# Generated by Django 3.0.5 on 2020-12-03 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupoun', '0003_delete_gencode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gencode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='OER', max_length=3)),
                ('codee', models.CharField(default='OERIP', max_length=5)),
                ('codeee', models.CharField(default='OERIPLO', max_length=7)),
            ],
        ),
    ]
