# Generated by Django 3.0.3 on 2020-11-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_is_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
