# Generated by Django 3.0.3 on 2020-11-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='total',
            field=models.IntegerField(),
        ),
    ]
