# Generated by Django 3.0.3 on 2020-11-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201103_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='total_like',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
