# Generated by Django 3.0.3 on 2020-11-02 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201103_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='total_like',
        ),
    ]
