# Generated by Django 3.0.3 on 2020-11-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_total_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='total_like',
            field=models.IntegerField(default=0),
        ),
    ]
