# Generated by Django 3.0.3 on 2020-11-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_post_total_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='total',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
