# Generated by Django 3.0.3 on 2020-11-02 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='total',
        ),
    ]
