# Generated by Django 3.0.3 on 2020-11-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_remove_post_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
